/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUserInfoRouteImport } from './routes/_authenticated/user-info'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRepositoriesRouteImport } from './routes/_authenticated/repositories'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedGpgkeysRouteImport } from './routes/_authenticated/gpgkeys'
import { Route as AuthenticatedClustersRouteImport } from './routes/_authenticated/clusters'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as AuthenticatedApplicationsNameRouteImport } from './routes/_authenticated/applications.$name'
import { Route as AuthenticatedApplicationsNameIndexRouteImport } from './routes/_authenticated/applications.$name/index'
import { Route as AuthenticatedApplicationsNameTreeRouteImport } from './routes/_authenticated/applications.$name/tree'
import { Route as AuthenticatedApplicationsNameSettingsRouteImport } from './routes/_authenticated/applications.$name/settings'
import { Route as AuthenticatedApplicationsNamePodsRouteImport } from './routes/_authenticated/applications.$name/pods'
import { Route as AuthenticatedApplicationsNameListRouteImport } from './routes/_authenticated/applications.$name/list'
import { Route as AuthenticatedApplicationsNameHistoryRouteImport } from './routes/_authenticated/applications.$name/history'
import { Route as AuthenticatedApplicationsNameDiffRouteImport } from './routes/_authenticated/applications.$name/diff'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserInfoRoute = AuthenticatedUserInfoRouteImport.update({
  id: '/user-info',
  path: '/user-info',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepositoriesRoute =
  AuthenticatedRepositoriesRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGpgkeysRoute = AuthenticatedGpgkeysRouteImport.update({
  id: '/gpgkeys',
  path: '/gpgkeys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClustersRoute = AuthenticatedClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedApplicationsNameRoute =
  AuthenticatedApplicationsNameRouteImport.update({
    id: '/$name',
    path: '/$name',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedApplicationsNameIndexRoute =
  AuthenticatedApplicationsNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApplicationsNameRoute,
  } as any)
const AuthenticatedApplicationsNameTreeRoute =
  AuthenticatedApplicationsNameTreeRouteImport.update({
    id: '/tree',
    path: '/tree',
    getParentRoute: () => AuthenticatedApplicationsNameRoute,
  } as any)
const AuthenticatedApplicationsNameSettingsRoute =
  AuthenticatedApplicationsNameSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedApplicationsNameRoute,
  } as any)
const AuthenticatedApplicationsNamePodsRoute =
  AuthenticatedApplicationsNamePodsRouteImport.update({
    id: '/pods',
    path: '/pods',
    getParentRoute: () => AuthenticatedApplicationsNameRoute,
  } as any)
const AuthenticatedApplicationsNameListRoute =
  AuthenticatedApplicationsNameListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedApplicationsNameRoute,
  } as any)
const AuthenticatedApplicationsNameHistoryRoute =
  AuthenticatedApplicationsNameHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedApplicationsNameRoute,
  } as any)
const AuthenticatedApplicationsNameDiffRoute =
  AuthenticatedApplicationsNameDiffRouteImport.update({
    id: '/diff',
    path: '/diff',
    getParentRoute: () => AuthenticatedApplicationsNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/clusters': typeof AuthenticatedClustersRoute
  '/gpgkeys': typeof AuthenticatedGpgkeysRoute
  '/help': typeof AuthenticatedHelpRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/repositories': typeof AuthenticatedRepositoriesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/user-info': typeof AuthenticatedUserInfoRoute
  '/': typeof AuthenticatedIndexRoute
  '/applications/$name': typeof AuthenticatedApplicationsNameRouteWithChildren
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/applications/$name/diff': typeof AuthenticatedApplicationsNameDiffRoute
  '/applications/$name/history': typeof AuthenticatedApplicationsNameHistoryRoute
  '/applications/$name/list': typeof AuthenticatedApplicationsNameListRoute
  '/applications/$name/pods': typeof AuthenticatedApplicationsNamePodsRoute
  '/applications/$name/settings': typeof AuthenticatedApplicationsNameSettingsRoute
  '/applications/$name/tree': typeof AuthenticatedApplicationsNameTreeRoute
  '/applications/$name/': typeof AuthenticatedApplicationsNameIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/clusters': typeof AuthenticatedClustersRoute
  '/gpgkeys': typeof AuthenticatedGpgkeysRoute
  '/help': typeof AuthenticatedHelpRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/repositories': typeof AuthenticatedRepositoriesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/user-info': typeof AuthenticatedUserInfoRoute
  '/': typeof AuthenticatedIndexRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/applications/$name/diff': typeof AuthenticatedApplicationsNameDiffRoute
  '/applications/$name/history': typeof AuthenticatedApplicationsNameHistoryRoute
  '/applications/$name/list': typeof AuthenticatedApplicationsNameListRoute
  '/applications/$name/pods': typeof AuthenticatedApplicationsNamePodsRoute
  '/applications/$name/settings': typeof AuthenticatedApplicationsNameSettingsRoute
  '/applications/$name/tree': typeof AuthenticatedApplicationsNameTreeRoute
  '/applications/$name': typeof AuthenticatedApplicationsNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/clusters': typeof AuthenticatedClustersRoute
  '/_authenticated/gpgkeys': typeof AuthenticatedGpgkeysRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/repositories': typeof AuthenticatedRepositoriesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/user-info': typeof AuthenticatedUserInfoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/applications/$name': typeof AuthenticatedApplicationsNameRouteWithChildren
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/applications/$name/diff': typeof AuthenticatedApplicationsNameDiffRoute
  '/_authenticated/applications/$name/history': typeof AuthenticatedApplicationsNameHistoryRoute
  '/_authenticated/applications/$name/list': typeof AuthenticatedApplicationsNameListRoute
  '/_authenticated/applications/$name/pods': typeof AuthenticatedApplicationsNamePodsRoute
  '/_authenticated/applications/$name/settings': typeof AuthenticatedApplicationsNameSettingsRoute
  '/_authenticated/applications/$name/tree': typeof AuthenticatedApplicationsNameTreeRoute
  '/_authenticated/applications/$name/': typeof AuthenticatedApplicationsNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/accounts'
    | '/applications'
    | '/certificates'
    | '/clusters'
    | '/gpgkeys'
    | '/help'
    | '/projects'
    | '/repositories'
    | '/settings'
    | '/user-info'
    | '/'
    | '/applications/$name'
    | '/applications/'
    | '/applications/$name/diff'
    | '/applications/$name/history'
    | '/applications/$name/list'
    | '/applications/$name/pods'
    | '/applications/$name/settings'
    | '/applications/$name/tree'
    | '/applications/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounts'
    | '/certificates'
    | '/clusters'
    | '/gpgkeys'
    | '/help'
    | '/projects'
    | '/repositories'
    | '/settings'
    | '/user-info'
    | '/'
    | '/applications'
    | '/applications/$name/diff'
    | '/applications/$name/history'
    | '/applications/$name/list'
    | '/applications/$name/pods'
    | '/applications/$name/settings'
    | '/applications/$name/tree'
    | '/applications/$name'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/accounts'
    | '/_authenticated/applications'
    | '/_authenticated/certificates'
    | '/_authenticated/clusters'
    | '/_authenticated/gpgkeys'
    | '/_authenticated/help'
    | '/_authenticated/projects'
    | '/_authenticated/repositories'
    | '/_authenticated/settings'
    | '/_authenticated/user-info'
    | '/_authenticated/'
    | '/_authenticated/applications/$name'
    | '/_authenticated/applications/'
    | '/_authenticated/applications/$name/diff'
    | '/_authenticated/applications/$name/history'
    | '/_authenticated/applications/$name/list'
    | '/_authenticated/applications/$name/pods'
    | '/_authenticated/applications/$name/settings'
    | '/_authenticated/applications/$name/tree'
    | '/_authenticated/applications/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user-info': {
      id: '/_authenticated/user-info'
      path: '/user-info'
      fullPath: '/user-info'
      preLoaderRoute: typeof AuthenticatedUserInfoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories': {
      id: '/_authenticated/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof AuthenticatedRepositoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gpgkeys': {
      id: '/_authenticated/gpgkeys'
      path: '/gpgkeys'
      fullPath: '/gpgkeys'
      preLoaderRoute: typeof AuthenticatedGpgkeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clusters': {
      id: '/_authenticated/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof AuthenticatedClustersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/applications/$name': {
      id: '/_authenticated/applications/$name'
      path: '/$name'
      fullPath: '/applications/$name'
      preLoaderRoute: typeof AuthenticatedApplicationsNameRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/applications/$name/': {
      id: '/_authenticated/applications/$name/'
      path: '/'
      fullPath: '/applications/$name/'
      preLoaderRoute: typeof AuthenticatedApplicationsNameIndexRouteImport
      parentRoute: typeof AuthenticatedApplicationsNameRoute
    }
    '/_authenticated/applications/$name/tree': {
      id: '/_authenticated/applications/$name/tree'
      path: '/tree'
      fullPath: '/applications/$name/tree'
      preLoaderRoute: typeof AuthenticatedApplicationsNameTreeRouteImport
      parentRoute: typeof AuthenticatedApplicationsNameRoute
    }
    '/_authenticated/applications/$name/settings': {
      id: '/_authenticated/applications/$name/settings'
      path: '/settings'
      fullPath: '/applications/$name/settings'
      preLoaderRoute: typeof AuthenticatedApplicationsNameSettingsRouteImport
      parentRoute: typeof AuthenticatedApplicationsNameRoute
    }
    '/_authenticated/applications/$name/pods': {
      id: '/_authenticated/applications/$name/pods'
      path: '/pods'
      fullPath: '/applications/$name/pods'
      preLoaderRoute: typeof AuthenticatedApplicationsNamePodsRouteImport
      parentRoute: typeof AuthenticatedApplicationsNameRoute
    }
    '/_authenticated/applications/$name/list': {
      id: '/_authenticated/applications/$name/list'
      path: '/list'
      fullPath: '/applications/$name/list'
      preLoaderRoute: typeof AuthenticatedApplicationsNameListRouteImport
      parentRoute: typeof AuthenticatedApplicationsNameRoute
    }
    '/_authenticated/applications/$name/history': {
      id: '/_authenticated/applications/$name/history'
      path: '/history'
      fullPath: '/applications/$name/history'
      preLoaderRoute: typeof AuthenticatedApplicationsNameHistoryRouteImport
      parentRoute: typeof AuthenticatedApplicationsNameRoute
    }
    '/_authenticated/applications/$name/diff': {
      id: '/_authenticated/applications/$name/diff'
      path: '/diff'
      fullPath: '/applications/$name/diff'
      preLoaderRoute: typeof AuthenticatedApplicationsNameDiffRouteImport
      parentRoute: typeof AuthenticatedApplicationsNameRoute
    }
  }
}

interface AuthenticatedApplicationsNameRouteChildren {
  AuthenticatedApplicationsNameDiffRoute: typeof AuthenticatedApplicationsNameDiffRoute
  AuthenticatedApplicationsNameHistoryRoute: typeof AuthenticatedApplicationsNameHistoryRoute
  AuthenticatedApplicationsNameListRoute: typeof AuthenticatedApplicationsNameListRoute
  AuthenticatedApplicationsNamePodsRoute: typeof AuthenticatedApplicationsNamePodsRoute
  AuthenticatedApplicationsNameSettingsRoute: typeof AuthenticatedApplicationsNameSettingsRoute
  AuthenticatedApplicationsNameTreeRoute: typeof AuthenticatedApplicationsNameTreeRoute
  AuthenticatedApplicationsNameIndexRoute: typeof AuthenticatedApplicationsNameIndexRoute
}

const AuthenticatedApplicationsNameRouteChildren: AuthenticatedApplicationsNameRouteChildren =
  {
    AuthenticatedApplicationsNameDiffRoute:
      AuthenticatedApplicationsNameDiffRoute,
    AuthenticatedApplicationsNameHistoryRoute:
      AuthenticatedApplicationsNameHistoryRoute,
    AuthenticatedApplicationsNameListRoute:
      AuthenticatedApplicationsNameListRoute,
    AuthenticatedApplicationsNamePodsRoute:
      AuthenticatedApplicationsNamePodsRoute,
    AuthenticatedApplicationsNameSettingsRoute:
      AuthenticatedApplicationsNameSettingsRoute,
    AuthenticatedApplicationsNameTreeRoute:
      AuthenticatedApplicationsNameTreeRoute,
    AuthenticatedApplicationsNameIndexRoute:
      AuthenticatedApplicationsNameIndexRoute,
  }

const AuthenticatedApplicationsNameRouteWithChildren =
  AuthenticatedApplicationsNameRoute._addFileChildren(
    AuthenticatedApplicationsNameRouteChildren,
  )

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsNameRoute: typeof AuthenticatedApplicationsNameRouteWithChildren
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsNameRoute:
      AuthenticatedApplicationsNameRouteWithChildren,
    AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedClustersRoute: typeof AuthenticatedClustersRoute
  AuthenticatedGpgkeysRoute: typeof AuthenticatedGpgkeysRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRepositoriesRoute: typeof AuthenticatedRepositoriesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUserInfoRoute: typeof AuthenticatedUserInfoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedClustersRoute: AuthenticatedClustersRoute,
  AuthenticatedGpgkeysRoute: AuthenticatedGpgkeysRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRepositoriesRoute: AuthenticatedRepositoriesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUserInfoRoute: AuthenticatedUserInfoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
